# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


# Class for video stream
class VideoDisplayWidget(QtWidgets.QWidget):
    def __init__(self,parent):
        super(VideoDisplayWidget, self).__init__(parent)        
        self.layout = QtWidgets.QFormLayout(self)
        self.setLayout(self.layout)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(920, 640)
        MainWindow.setMinimumSize(QtCore.QSize(920, 640))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 1024))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 10, 901, 621))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_10.setMinimumSize(QtCore.QSize(50, 20))
        self.label_10.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_11.addWidget(self.label_10)
        self.tableIsObject = QtWidgets.QTableWidget(self.verticalLayoutWidget_7)
        self.tableIsObject.setMinimumSize(QtCore.QSize(200, 50))
        self.tableIsObject.setMaximumSize(QtCore.QSize(200, 50))
        self.tableIsObject.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableIsObject.setTabKeyNavigation(False)
        self.tableIsObject.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableIsObject.setObjectName("tableIsObject")
        self.tableIsObject.setColumnCount(2)
        self.tableIsObject.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableIsObject.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableIsObject.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableIsObject.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableIsObject.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableIsObject.setItem(0, 1, item)
        self.tableIsObject.horizontalHeader().setDefaultSectionSize(99)
        self.tableIsObject.horizontalHeader().setHighlightSections(False)
        self.tableIsObject.horizontalHeader().setMinimumSectionSize(99)
        self.tableIsObject.horizontalHeader().setStretchLastSection(False)
        self.tableIsObject.verticalHeader().setVisible(False)
        self.tableIsObject.verticalHeader().setDefaultSectionSize(30)
        self.tableIsObject.verticalHeader().setHighlightSections(False)
        self.tableIsObject.verticalHeader().setMinimumSectionSize(30)
        self.tableIsObject.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_11.addWidget(self.tableIsObject)
        self.horizontalLayout_2.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_16.setMinimumSize(QtCore.QSize(50, 20))
        self.label_16.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_12.addWidget(self.label_16)
        self.tableIsNoise = QtWidgets.QTableWidget(self.verticalLayoutWidget_7)
        self.tableIsNoise.setMinimumSize(QtCore.QSize(200, 50))
        self.tableIsNoise.setMaximumSize(QtCore.QSize(200, 50))
        self.tableIsNoise.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableIsNoise.setTabKeyNavigation(False)
        self.tableIsNoise.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableIsNoise.setObjectName("tableIsNoise")
        self.tableIsNoise.setColumnCount(2)
        self.tableIsNoise.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableIsNoise.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableIsNoise.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableIsNoise.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableIsNoise.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableIsNoise.setItem(0, 1, item)
        self.tableIsNoise.horizontalHeader().setDefaultSectionSize(99)
        self.tableIsNoise.horizontalHeader().setHighlightSections(False)
        self.tableIsNoise.horizontalHeader().setMinimumSectionSize(99)
        self.tableIsNoise.horizontalHeader().setStretchLastSection(False)
        self.tableIsNoise.verticalHeader().setVisible(False)
        self.tableIsNoise.verticalHeader().setDefaultSectionSize(30)
        self.tableIsNoise.verticalHeader().setHighlightSections(False)
        self.tableIsNoise.verticalHeader().setMinimumSectionSize(30)
        self.tableIsNoise.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_12.addWidget(self.tableIsNoise)
        self.horizontalLayout_2.addLayout(self.verticalLayout_12)
        self.verticalLayout_10.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_17.setMinimumSize(QtCore.QSize(50, 20))
        self.label_17.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_13.addWidget(self.label_17)
        self.tableZoneCount = QtWidgets.QTableWidget(self.verticalLayoutWidget_7)
        self.tableZoneCount.setMinimumSize(QtCore.QSize(200, 90))
        self.tableZoneCount.setMaximumSize(QtCore.QSize(200, 90))
        self.tableZoneCount.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableZoneCount.setTabKeyNavigation(False)
        self.tableZoneCount.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableZoneCount.setObjectName("tableZoneCount")
        self.tableZoneCount.setColumnCount(2)
        self.tableZoneCount.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableZoneCount.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableZoneCount.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableZoneCount.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableZoneCount.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableZoneCount.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableZoneCount.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableZoneCount.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableZoneCount.setItem(1, 1, item)
        self.tableZoneCount.horizontalHeader().setDefaultSectionSize(90)
        self.tableZoneCount.horizontalHeader().setMinimumSectionSize(90)
        self.tableZoneCount.horizontalHeader().setStretchLastSection(True)
        self.tableZoneCount.verticalHeader().setVisible(True)
        self.tableZoneCount.verticalHeader().setCascadingSectionResizes(False)
        self.tableZoneCount.verticalHeader().setDefaultSectionSize(30)
        self.tableZoneCount.verticalHeader().setHighlightSections(True)
        self.tableZoneCount.verticalHeader().setMinimumSectionSize(30)
        self.tableZoneCount.verticalHeader().setSortIndicatorShown(False)
        self.tableZoneCount.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_13.addWidget(self.tableZoneCount)
        self.horizontalLayout_3.addLayout(self.verticalLayout_13)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setSpacing(2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_11.setMinimumSize(QtCore.QSize(50, 20))
        self.label_11.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_15.addWidget(self.label_11)
        self.tableZoneRef = QtWidgets.QTableWidget(self.verticalLayoutWidget_7)
        self.tableZoneRef.setMinimumSize(QtCore.QSize(200, 50))
        self.tableZoneRef.setMaximumSize(QtCore.QSize(200, 50))
        self.tableZoneRef.setTabKeyNavigation(False)
        self.tableZoneRef.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableZoneRef.setObjectName("tableZoneRef")
        self.tableZoneRef.setColumnCount(3)
        self.tableZoneRef.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableZoneRef.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableZoneRef.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableZoneRef.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableZoneRef.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableZoneRef.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableZoneRef.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableZoneRef.setItem(0, 2, item)
        self.tableZoneRef.horizontalHeader().setDefaultSectionSize(66)
        self.tableZoneRef.horizontalHeader().setMinimumSectionSize(66)
        self.tableZoneRef.horizontalHeader().setStretchLastSection(True)
        self.tableZoneRef.verticalHeader().setVisible(False)
        self.tableZoneRef.verticalHeader().setMinimumSectionSize(30)
        self.tableZoneRef.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_15.addWidget(self.tableZoneRef)
        self.horizontalLayout_3.addLayout(self.verticalLayout_15)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setSpacing(2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_18.setMinimumSize(QtCore.QSize(50, 20))
        self.label_18.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_14.addWidget(self.label_18)
        self.tableRefColourBord = QtWidgets.QTableWidget(self.verticalLayoutWidget_7)
        self.tableRefColourBord.setMinimumSize(QtCore.QSize(200, 90))
        self.tableRefColourBord.setMaximumSize(QtCore.QSize(200, 90))
        self.tableRefColourBord.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableRefColourBord.setTabKeyNavigation(False)
        self.tableRefColourBord.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableRefColourBord.setGridStyle(QtCore.Qt.SolidLine)
        self.tableRefColourBord.setObjectName("tableRefColourBord")
        self.tableRefColourBord.setColumnCount(3)
        self.tableRefColourBord.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableRefColourBord.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRefColourBord.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRefColourBord.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRefColourBord.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRefColourBord.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableRefColourBord.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableRefColourBord.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableRefColourBord.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableRefColourBord.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableRefColourBord.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableRefColourBord.setItem(1, 2, item)
        self.tableRefColourBord.horizontalHeader().setDefaultSectionSize(55)
        self.tableRefColourBord.horizontalHeader().setMinimumSectionSize(55)
        self.tableRefColourBord.horizontalHeader().setStretchLastSection(True)
        self.tableRefColourBord.verticalHeader().setVisible(True)
        self.tableRefColourBord.verticalHeader().setDefaultSectionSize(30)
        self.tableRefColourBord.verticalHeader().setMinimumSectionSize(30)
        self.tableRefColourBord.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_14.addWidget(self.tableRefColourBord)
        self.horizontalLayout_5.addLayout(self.verticalLayout_14)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSpacing(2)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_13.setMinimumSize(QtCore.QSize(120, 20))
        self.label_13.setMaximumSize(QtCore.QSize(145, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        self.numberPixels = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.numberPixels.setMinimumSize(QtCore.QSize(80, 30))
        self.numberPixels.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.numberPixels.setFont(font)
        self.numberPixels.setObjectName("numberPixels")
        self.horizontalLayout_7.addWidget(self.numberPixels)
        self.verticalLayout_16.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_12.setMinimumSize(QtCore.QSize(120, 20))
        self.label_12.setMaximumSize(QtCore.QSize(145, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.refColourHSV = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.refColourHSV.setMinimumSize(QtCore.QSize(80, 30))
        self.refColourHSV.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.refColourHSV.setFont(font)
        self.refColourHSV.setObjectName("refColourHSV")
        self.horizontalLayout_8.addWidget(self.refColourHSV)
        self.verticalLayout_16.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5.addLayout(self.verticalLayout_16)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.btnEnCalibrParam = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.btnEnCalibrParam.setMinimumSize(QtCore.QSize(150, 20))
        self.btnEnCalibrParam.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.btnEnCalibrParam.setFont(font)
        self.btnEnCalibrParam.setCheckable(True)
        self.btnEnCalibrParam.setAutoRepeatDelay(50)
        self.btnEnCalibrParam.setAutoRepeatInterval(50)
        self.btnEnCalibrParam.setObjectName("btnEnCalibrParam")
        self.verticalLayout_10.addWidget(self.btnEnCalibrParam)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)


        # Video stream:
        self.videoContainer = VideoDisplayWidget(self)        
        self.videoContainer.setObjectName("videoContainer")
        
        self.horizontalLayout_4.addWidget(self.videoContainer)

        
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_7.setMinimumSize(QtCore.QSize(50, 30))
        self.label_7.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.productCurr = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.productCurr.setMinimumSize(QtCore.QSize(200, 50))
        self.productCurr.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.productCurr.setFont(font)
        self.productCurr.setFrameShape(QtWidgets.QFrame.Box)
        self.productCurr.setAlignment(QtCore.Qt.AlignCenter)
        self.productCurr.setObjectName("productCurr")
        self.verticalLayout_8.addWidget(self.productCurr)
        self.verticalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_3.setMinimumSize(QtCore.QSize(50, 30))
        self.label_3.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.numberProductInBox = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.numberProductInBox.setMinimumSize(QtCore.QSize(200, 50))
        self.numberProductInBox.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.numberProductInBox.setFont(font)
        self.numberProductInBox.setFrameShape(QtWidgets.QFrame.Box)
        self.numberProductInBox.setAlignment(QtCore.Qt.AlignCenter)
        self.numberProductInBox.setObjectName("numberProductInBox")
        self.verticalLayout.addWidget(self.numberProductInBox)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_4.setMinimumSize(QtCore.QSize(50, 20))
        self.label_4.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.numberProductCons = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.numberProductCons.setMinimumSize(QtCore.QSize(200, 30))
        self.numberProductCons.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.numberProductCons.setFont(font)
        self.numberProductCons.setFrameShape(QtWidgets.QFrame.Box)
        self.numberProductCons.setFrameShadow(QtWidgets.QFrame.Plain)
        self.numberProductCons.setAlignment(QtCore.Qt.AlignCenter)
        self.numberProductCons.setObjectName("numberProductCons")
        self.verticalLayout_3.addWidget(self.numberProductCons)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_2.setMinimumSize(QtCore.QSize(50, 20))
        self.label_2.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.numberProductAll = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.numberProductAll.setMinimumSize(QtCore.QSize(200, 30))
        self.numberProductAll.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.numberProductAll.setFont(font)
        self.numberProductAll.setFrameShape(QtWidgets.QFrame.Box)
        self.numberProductAll.setAlignment(QtCore.Qt.AlignCenter)
        self.numberProductAll.setObjectName("numberProductAll")
        self.verticalLayout_2.addWidget(self.numberProductAll)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_6.setMinimumSize(QtCore.QSize(50, 20))
        self.label_6.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.timer = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.timer.setMinimumSize(QtCore.QSize(200, 30))
        self.timer.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.timer.setFont(font)
        self.timer.setFrameShape(QtWidgets.QFrame.Box)
        self.timer.setAlignment(QtCore.Qt.AlignCenter)
        self.timer.setObjectName("timer")
        self.verticalLayout_5.addWidget(self.timer)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_5.setMinimumSize(QtCore.QSize(350, 20))
        self.label_5.setMaximumSize(QtCore.QSize(450, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.listProduct = QtWidgets.QComboBox(self.verticalLayoutWidget_7)
        self.listProduct.setMinimumSize(QtCore.QSize(350, 30))
        self.listProduct.setMaximumSize(QtCore.QSize(450, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listProduct.setFont(font)
        self.listProduct.setObjectName("listProduct")
        self.verticalLayout_9.addWidget(self.listProduct)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label.setMinimumSize(QtCore.QSize(300, 20))
        self.label.setMaximumSize(QtCore.QSize(450, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.inputProductNumber = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.inputProductNumber.setMinimumSize(QtCore.QSize(300, 30))
        self.inputProductNumber.setMaximumSize(QtCore.QSize(450, 30))
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.inputProductNumber.setFont(font)
        self.inputProductNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.inputProductNumber.setObjectName("inputProductNumber")
        self.verticalLayout_6.addWidget(self.inputProductNumber)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnCatalog = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.btnCatalog.setMinimumSize(QtCore.QSize(150, 20))
        self.btnCatalog.setMaximumSize(QtCore.QSize(240, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.btnCatalog.setFont(font)
        self.btnCatalog.setObjectName("btnCatalog")
        self.horizontalLayout_6.addWidget(self.btnCatalog)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btnStop = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.btnStop.setMinimumSize(QtCore.QSize(100, 20))
        self.btnStop.setMaximumSize(QtCore.QSize(140, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.btnStop.setFont(font)
        self.btnStop.setStyleSheet("background-color: rgb(255, 0, 51);")
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout_9.addWidget(self.btnStop)
        self.btnStart = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.btnStart.setMinimumSize(QtCore.QSize(100, 20))
        self.btnStart.setMaximumSize(QtCore.QSize(140, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.btnStart.setFont(font)
        self.btnStart.setStyleSheet("background-color: rgb(51, 204, 153);")
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout_9.addWidget(self.btnStart)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Омский Бекон. Счёт продукции"))
        self.label_10.setText(_translate("MainWindow", "Порог наличия объекта (Pix):"))
        item = self.tableIsObject.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Px"))
        item = self.tableIsObject.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Min"))
        item = self.tableIsObject.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Max"))
        __sortingEnabled = self.tableIsObject.isSortingEnabled()
        self.tableIsObject.setSortingEnabled(False)
        self.tableIsObject.setSortingEnabled(__sortingEnabled)
        self.label_16.setText(_translate("MainWindow", "Порог наличия шумов (Pix):"))
        item = self.tableIsNoise.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Px"))
        item = self.tableIsNoise.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Min"))
        item = self.tableIsNoise.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Max"))
        __sortingEnabled = self.tableIsNoise.isSortingEnabled()
        self.tableIsNoise.setSortingEnabled(False)
        self.tableIsNoise.setSortingEnabled(__sortingEnabled)
        self.label_17.setText(_translate("MainWindow", "Положение Зоны подсчёта (Pix):"))
        item = self.tableZoneCount.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "X"))
        item = self.tableZoneCount.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Y"))
        item = self.tableZoneCount.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Start"))
        item = self.tableZoneCount.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "End"))
        __sortingEnabled = self.tableZoneCount.isSortingEnabled()
        self.tableZoneCount.setSortingEnabled(False)
        self.tableZoneCount.setSortingEnabled(__sortingEnabled)
        self.label_11.setText(_translate("MainWindow", "Положение Опорной зоны (Pix):"))
        item = self.tableZoneRef.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Px"))
        item = self.tableZoneRef.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "X"))
        item = self.tableZoneRef.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Y"))
        item = self.tableZoneRef.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Size"))
        __sortingEnabled = self.tableZoneRef.isSortingEnabled()
        self.tableZoneRef.setSortingEnabled(False)
        self.tableZoneRef.setSortingEnabled(__sortingEnabled)
        self.label_18.setText(_translate("MainWindow", "Границы опорного цвета (0-255):"))
        item = self.tableRefColourBord.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Min"))
        item = self.tableRefColourBord.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Max"))
        item = self.tableRefColourBord.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "H"))
        item = self.tableRefColourBord.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "S"))
        item = self.tableRefColourBord.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "V"))
        __sortingEnabled = self.tableRefColourBord.isSortingEnabled()
        self.tableRefColourBord.setSortingEnabled(False)
        self.tableRefColourBord.setSortingEnabled(__sortingEnabled)
        self.label_13.setText(_translate("MainWindow", "Пикселей в зоне:"))
        self.numberPixels.setText(_translate("MainWindow", "numberPixels_h"))
        self.label_12.setText(_translate("MainWindow", "Опорный цвет HSV:"))
        self.refColourHSV.setText(_translate("MainWindow", "ref_hsv"))
        self.btnEnCalibrParam.setText(_translate("MainWindow", "Параметры калибровки"))
        self.label_7.setText(_translate("MainWindow", "Текущий продукт:"))
        self.productCurr.setText(_translate("MainWindow", "ProdCurr"))
        self.label_3.setText(_translate("MainWindow", "Всего в коробке:"))
        self.numberProductInBox.setText(_translate("MainWindow", "Box"))
        self.label_4.setText(_translate("MainWindow", "Коробок текущего продукта:"))
        self.numberProductCons.setText(_translate("MainWindow", "Cons"))
        self.label_2.setText(_translate("MainWindow", "Всего за смену:"))
        self.numberProductAll.setText(_translate("MainWindow", "All"))
        self.label_6.setText(_translate("MainWindow", "Время смены:"))
        self.timer.setText(_translate("MainWindow", "Время"))
        self.label_5.setText(_translate("MainWindow", "Выберите продукт из списка:"))
        self.label.setText(_translate("MainWindow", "Или введите артикул продукта:"))
        self.btnCatalog.setText(_translate("MainWindow", "Каталог"))
        self.btnStop.setText(_translate("MainWindow", "Стоп"))
        self.btnStart.setText(_translate("MainWindow", "Старт"))
